language: java

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - libgtk-3-dev
    - os: osx
      osx_image: xcode10.2

script:
  - ./gradlew build
